#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/abc-voice

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: sudo npm i -g serverless
      - run:
          name: Deploy application
          command: serverless deploy --stage pre
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
